"""change grade value data type

Revision ID: f0805b79fa9b
Revises: aa7b1c4505a0
Create Date: 2023-08-06 13:25:39.300104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0805b79fa9b'
down_revision: Union[str, None] = 'aa7b1c4505a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
